/**
 * Build script to generate base64-encoded icon data for OG image generation.
 * 
 * Run with: npx tsx scripts/generate-icon-data.ts
 * 
 * Resizes icons to 64x64 before encoding to reduce bundle size.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'
import { fileURLToPath } from 'url'
import sharp from 'sharp'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const iconsDir = join(__dirname, '../public/icons')
const outputFile = join(__dirname, '../src/lib/iconData.ts')

// Target size for OG images (64x64 is plenty for preview)
const TARGET_SIZE = 64

// Icons to include
const INCLUDE_ICONS = [
    // Roles
    'tank', 'tank_1', 'tank_2',
    'healer', 'healer_1', 'healer_2',
    'dps', 'dps_1', 'dps_2', 'dps_3', 'dps_4',
    'melee_dps', 'ranged_dps', 'physical_ranged_dps', 'magical_ranged_dps',
    'melee_1', 'melee_2', 'ranged_dps_1', 'ranged_dps_2',

    // Waymarks
    'waymark_a', 'waymark_b', 'waymark_c', 'waymark_d',
    'waymark_1', 'waymark_2', 'waymark_3', 'waymark_4',

    // Enemies
    'small_enemy', 'medium_enemy', 'large_enemy',

    // Markers
    'attack_1', 'attack_2', 'attack_3', 'attack_4',
    'attack_5', 'attack_6', 'attack_7', 'attack_8',
    'bind_1', 'bind_2', 'bind_3',
    'ignore_1', 'ignore_2',
    'circle_marker', 'square_marker', 'triangle_marker', 'plus_marker',
    'lockon_red', 'lockon_blue', 'lockon_purple', 'lockon_green',

    // Shapes
    'shape_circle', 'shape_square', 'shape_triangle', 'shape_x',
    'up_arrow', 'rotate', 'rotate_clockwise', 'rotate_counterclockwise',
    'highlighted_circle', 'highlighted_x', 'highlighted_square', 'highlighted_triangle',

    // Buffs/Debuffs
    'enhancement', 'enfeeblement',

    // Mechanics (with count support)
    'linear_knockback', 'radial_knockback', 'line_stack',
    'stack', 'stack_multi', 'gaze', 'proximity', 'proximity_player',
    'tankbuster', 'tower', 'targeting', 'moving_circle_aoe',

    // Jobs - Tanks
    'paladin', 'warrior', 'dark_knight', 'gunbreaker',
    'gladiator', 'marauder',

    // Jobs - Healers
    'white_mage', 'scholar', 'astrologian', 'sage',
    'conjurer', 'pure_healer', 'barrier_healer',

    // Jobs - Melee DPS
    'monk', 'dragoon', 'ninja', 'samurai', 'reaper', 'viper',
    'pugilist', 'lancer', 'rogue',

    // Jobs - Physical Ranged DPS
    'bard', 'machinist', 'dancer',
    'archer',

    // Jobs - Magical Ranged DPS
    'black_mage', 'summoner', 'red_mage', 'pictomancer', 'blue_mage',
    'thaumaturge', 'arcanist',
]

async function generateIconData() {
    const iconData: Record<string, string> = {}
    let totalSize = 0
    let originalSize = 0

    for (const iconName of INCLUDE_ICONS) {
        const iconPath = join(iconsDir, `${iconName}.png`)

        if (!existsSync(iconPath)) {
            console.warn(`Warning: Icon not found: ${iconName}.png`)
            continue
        }

        try {
            const originalBuffer = readFileSync(iconPath)
            originalSize += originalBuffer.length

            // Resize to TARGET_SIZE x TARGET_SIZE
            const resizedBuffer = await sharp(originalBuffer)
                .resize(TARGET_SIZE, TARGET_SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
                .png({ quality: 80 })
                .toBuffer()

            const base64 = resizedBuffer.toString('base64')
            iconData[iconName] = `data:image/png;base64,${base64}`
            totalSize += resizedBuffer.length

            const reduction = ((1 - resizedBuffer.length / originalBuffer.length) * 100).toFixed(0)
            console.log(`✓ ${iconName}.png ${(originalBuffer.length / 1024).toFixed(1)}KB → ${(resizedBuffer.length / 1024).toFixed(1)}KB (-${reduction}%)`)
        } catch (error) {
            console.error(`Error processing ${iconName}.png:`, error)
        }
    }

    // Generate TypeScript file
    const tsContent = `/**
 * Auto-generated icon data for OG image generation.
 * Generated by: npx tsx scripts/generate-icon-data.ts
 * 
 * Icons resized to ${TARGET_SIZE}x${TARGET_SIZE} for smaller bundle.
 * Total icons: ${Object.keys(iconData).length}
 * Original size: ${(originalSize / 1024).toFixed(1)} KB
 * Compressed size: ${(totalSize / 1024).toFixed(1)} KB
 */

export const iconData: Record<string, string> = ${JSON.stringify(iconData, null, 2)}

export function getIconDataUrl(type: string): string | null {
  return iconData[type] ?? null
}
`

    writeFileSync(outputFile, tsContent)
    console.log(`\n✅ Generated ${outputFile}`)
    console.log(`   Total icons: ${Object.keys(iconData).length}`)
    console.log(`   Original size: ${(originalSize / 1024).toFixed(1)} KB`)
    console.log(`   Compressed size: ${(totalSize / 1024).toFixed(1)} KB`)
    console.log(`   Reduction: ${((1 - totalSize / originalSize) * 100).toFixed(0)}%`)
}

generateIconData()
