/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CreateRouteImport } from './routes/create'
import { Route as BRouteImport } from './routes/b'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCodeRouteImport } from './routes/c/$code'
import { Route as BShareCodeRouteImport } from './routes/b.$shareCode'
import { Route as ApiOgRouteImport } from './routes/api.og'
import { Route as ApiBundlesRouteImport } from './routes/api.bundles'

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BRoute = BRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BShareCodeRoute = BShareCodeRouteImport.update({
  id: '/$shareCode',
  path: '/$shareCode',
  getParentRoute: () => BRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBundlesRoute = ApiBundlesRouteImport.update({
  id: '/api/bundles',
  path: '/api/bundles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/b': typeof BRouteWithChildren
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/api/bundles': typeof ApiBundlesRoute
  '/api/og': typeof ApiOgRoute
  '/b/$shareCode': typeof BShareCodeRoute
  '/c/$code': typeof CCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/b': typeof BRouteWithChildren
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/api/bundles': typeof ApiBundlesRoute
  '/api/og': typeof ApiOgRoute
  '/b/$shareCode': typeof BShareCodeRoute
  '/c/$code': typeof CCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/b': typeof BRouteWithChildren
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/api/bundles': typeof ApiBundlesRoute
  '/api/og': typeof ApiOgRoute
  '/b/$shareCode': typeof BShareCodeRoute
  '/c/$code': typeof CCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/b'
    | '/create'
    | '/import'
    | '/api/bundles'
    | '/api/og'
    | '/b/$shareCode'
    | '/c/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/b'
    | '/create'
    | '/import'
    | '/api/bundles'
    | '/api/og'
    | '/b/$shareCode'
    | '/c/$code'
  id:
    | '__root__'
    | '/'
    | '/$code'
    | '/b'
    | '/create'
    | '/import'
    | '/api/bundles'
    | '/api/og'
    | '/b/$shareCode'
    | '/c/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  BRoute: typeof BRouteWithChildren
  CreateRoute: typeof CreateRoute
  ImportRoute: typeof ImportRoute
  ApiBundlesRoute: typeof ApiBundlesRoute
  ApiOgRoute: typeof ApiOgRoute
  CCodeRoute: typeof CCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$shareCode': {
      id: '/b/$shareCode'
      path: '/$shareCode'
      fullPath: '/b/$shareCode'
      preLoaderRoute: typeof BShareCodeRouteImport
      parentRoute: typeof BRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bundles': {
      id: '/api/bundles'
      path: '/api/bundles'
      fullPath: '/api/bundles'
      preLoaderRoute: typeof ApiBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BRouteChildren {
  BShareCodeRoute: typeof BShareCodeRoute
}

const BRouteChildren: BRouteChildren = {
  BShareCodeRoute: BShareCodeRoute,
}

const BRouteWithChildren = BRoute._addFileChildren(BRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  BRoute: BRouteWithChildren,
  CreateRoute: CreateRoute,
  ImportRoute: ImportRoute,
  ApiBundlesRoute: ApiBundlesRoute,
  ApiOgRoute: ApiOgRoute,
  CCodeRoute: CCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
